#!/bin/sh
# Init script for aesdsocket. Installed as /etc/init.d/S99aesdsocket.
# start: launches aesdsocket in daemon mode (-d)
# stop:  sends SIGTERM so aesdsocket closes its sockets and deletes
#        /var/tmp/aesdsocketdata before exiting

DAEMON=/usr/bin/aesdsocket
NAME=aesdsocket

case "$1" in
    start)
        echo "Starting ${NAME}"
        start-stop-daemon -S -n ${NAME} -a ${DAEMON} -- -d
        ;;
    stop)
        echo "Stopping ${NAME}"
        start-stop-daemon -K -n ${NAME} -s TERM
        ;;
    restart)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
